#!/bin/bash
echo "a"
echo $SLACK_ORG
env
# echo "***** Installing slackin npm module" && \
# npm install -g slackin && \
# echo "***** Installed slacking npm module" && \
# echo "***** Starting slackin" && \
# exec slackin -t $SLACK_TOKEN -o $SLACK_ORG